{% set name = "xgboost" %}
{% set version = "0.72" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/dmlc/xgboost
  # corresponds to 0.72 tag
  git_tag: 1214081f994c3798703a035419aafb84716c3cba
  patches:
    # xgboost patches
    - 0001-conda-Unbundle-libxgboost.-dll-dylib-so.patch
    - 0002-Fix-R-package-PKGROOT.patch
    - 0003-Fix-R-package-mingw-w64-compiler-flags-remove-m64.patch
    - 0004-Fix-configure-check-for-OpenMP-on-macOS.patch
    - 0005-Add-ADD_-FLAGS-to-end-of-commandlines.patch

build:
  skip: true  # [win32 or linux32]
  rpaths:
    - lib/R/lib
  merge_build_host: True  # [win]

outputs:

  - name: _r-xgboost-mutex
    version: 1.0
    build:
      string: gpu_0

  - name: r-xgboost
    script: install-r-xgboost.sh      # [linux]
    script: install-r-xgboost.bat     # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - git                         # [linux]
        - make                        # [linux]
        {% if r_implementation == "mro-base" %}
        - rtools                      # [win]
        {% else %}
        - m2w64-toolchain             # [win]
        {% endif %}
      host:
        # GPU requirements
        - cudatoolkit {{ cudatoolkit }}*
        - {{ r_implementation }}
        - r-matrix
        - r-data.table
        - r-magrittr
        - r-stringi
        - r-knitr
      run:
        - cudatoolkit {{ cudatoolkit }}*
        - {{ r_implementation }}
        - {{ pin_subpackage('_r-xgboost-mutex', exact=True) }}
        - r-matrix
        - r-data.table
        - r-magrittr
        - r-stringi

  - name: r-xgboost-gpu
    requirements:
      host:
        - {{ r_implementation }}
      run:
        - {{ r_implementation }}
        - {{ pin_subpackage('r-xgboost', exact=True) }}
    test:
      files:
        - test-r-xgboost.r
      commands:
        - Rscript test-r-xgboost.r
    # present to include cuda version in hash
    extra:
      toolkitused: {{ cudatoolkit }}
